version: '3.4'

services:
  seqserver:
    image: datalust/seq:latest
    restart: always
    container_name: hostcoredocker-seqserver
    ports:
      - "5341:80"
    environment: 
      - ACCEPT_EULA=Y
    volumes: 
      - C:\DockerVolMount\dev\seqdata:/data
    entrypoint: /run.sh
  hostcoredocker:
    image: hostcoredocker
    build:
      context: .
      dockerfile: HostCoreDocker/Dockerfile
